// generated by stringer -type=TokenType; DO NOT EDIT

package lexer

import "fmt"

const _TokenType_name = "TOKEN_RUNETOKEN_IDENTIFIERTOKEN_SEPARATORTOKEN_OPERATORTOKEN_NUMBERTOKEN_ERRONEOUSTOKEN_STRINGTOKEN_UNKNOWNTOKEN_END_OF_FILE"

var _TokenType_index = [...]uint8{10, 26, 41, 55, 67, 82, 94, 107, 124}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)) {
		return fmt.Sprintf("TokenType(%d)", i)
	}
	hi := _TokenType_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _TokenType_index[i-1]
	}
	return _TokenType_name[lo:hi]
}
