// generated by stringer -type=BinOpType; DO NOT EDIT

package parser

import "fmt"

const _BinOpType_name = "BINOP_ERRBINOP_ADDBINOP_SUBBINOP_MULBINOP_DIVBINOP_MODBINOP_GREATERBINOP_LESSBINOP_GREATER_EQBINOP_LESS_EQBINOP_EQBINOP_NOT_EQBINOP_BIT_ANDBINOP_BIT_ORBINOP_BIT_XORBINOP_BIT_LEFTBINOP_BIT_RIGHTBINOP_LOG_ANDBINOP_LOG_OR"

var _BinOpType_index = [...]uint8{9, 18, 27, 36, 45, 54, 67, 77, 93, 106, 114, 126, 139, 151, 164, 178, 193, 206, 218}

func (i BinOpType) String() string {
	if i < 0 || i >= BinOpType(len(_BinOpType_index)) {
		return fmt.Sprintf("BinOpType(%d)", i)
	}
	hi := _BinOpType_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _BinOpType_index[i-1]
	}
	return _BinOpType_name[lo:hi]
}
